/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkPerry' at '12/07/15 9:11 PM' with Gradle 2.4
 *
 * @author MarkPerry, @date 12/07/15 9:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
